name = "cefpfc 1.18"
author = "copygirl"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a66db2a6a6c8bff25cb7b64cab4a3118b9aefbd6282ba566efa772dcbb02ac6"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
