name = "cefpfc 1.18"
author = "copygirl"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5857334d25e46fcf15d06052337b50e7b615d2824a87c7be2bb1196b9be5bba"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
