name = "cefpfc 1.18"
author = "copygirl"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f15bb1ce4560de31d7bcc3bfb7647f617d2ba836c3c78ae0bc0dcfa109e10d87"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
