name = "cefpfc 1.18"
author = "copygirl"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "324dbb67cba7f3eeb0a4d58d3a55e61f9fda2d2aa18296962d3f423c4467b06e"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
