enablePinning = false
darkMode = false
keepCentered = true
settingsButton = true
enableBook = true

[newRecipes]
unlockAll = true
enableBounce = false

[instantCraft]
showButton = true

[alternativeRecipes]
onHover = false
noGrouped = false

[scrolling]
enableScrolling = true
scrollAround = true
