name = "Axolotl Bucket Fix"
filename = "axolotl-item-fix-1.1.3.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3515/755/axolotl-item-fix-1.1.3.jar"
hash-format = "sha1"
hash = "f60f9ea1e6afded2935ba5b1406aedcf429c20f8"

[update]
[update.curseforge]
file-id = 3515755
project-id = 495453
