name = "Bedspreads (Fabric)"
filename = "bedspreads-fabric-1.5.0-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3555/943/bedspreads-fabric-1.5.0-1.18.jar"
hash-format = "sha1"
hash = "0d3bcda536ba4b38314d52a5c5d518bda8565f3c"

[update]
[update.curseforge]
file-id = 3555943
project-id = 400477
