name = "Decorative Blocks"
filename = "Decorative Blocks-fabric-1.18.2-2.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3681/918/Decorative%20Blocks-fabric-1.18.2-2.1.0.jar"
hash-format = "sha1"
hash = "2574749d52b69cea643898ddf0dc977be174f13e"

[update]
[update.curseforge]
file-id = 3681918
project-id = 362528
