name = "Fabrication"
filename = "fabrication-1.18.2-2.3.1-exp3.jar"
side = "both"

[download]
url = "https://github.com/unascribed/Fabrication/releases/download/v2.3.0/fabrication-1.18.2-2.3.1-exp3.jar"
hash-format = "sha1"
hash = "3d84e11b1ac13d0829bb85d14ffc7ef11306d58d"
