name = "Falling Leaves"
filename = "fallingleaves-1.11.0+1.18.2.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/WhbRG4iK/versions/1.11.0/fallingleaves-1.11.0%2B1.18.2.jar"
hash-format = "sha1"
hash = "22f261899a05e8edce3d351b36a16be4a26d7f37"

[update]
[update.modrinth]
mod-id = "WhbRG4iK"
version = "KlJ03K3I"
