name = "Grind Enchantments"
filename = "grind-enchantments-1.6.1+1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/WC4UgDcZ/versions/1.6.1/grind-enchantments-1.6.1%2B1.18.2.jar"
hash-format = "sha1"
hash = "7077e120f6f41d5a927e81f7c4dab851c8660e8c"

[update]
[update.modrinth]
mod-id = "WC4UgDcZ"
version = "YgkcQnAa"
