name = "More Axolotl Variants Mod"
filename = "mavm-fabric-1.18.1-1.0.7a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3590/362/mavm-fabric-1.18.1-1.0.7a.jar"
hash-format = "sha1"
hash = "904c69a69c46695c75eee1e009310274d97ce48a"

[update]
[update.curseforge]
file-id = 3590362
project-id = 498797
