name = "RSWires"
filename = "rswires-4.13.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3667/421/rswires-4.13.0.jar"
hash-format = "sha1"
hash = "876e58d1728e35c642f9b35319642a5887b15afd"

[update]
[update.curseforge]
file-id = 3667421
project-id = 286328
