name = "Spectrum"
filename = "spectrum-1.3.0-1.18.2-midgame15-trinkets-brewing.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/3rc31Hgo/versions/1.3.0/spectrum-1.3.0-1.18.2-midgame15-trinkets-brewing.jar"
hash-format = "sha1"
hash = "fd96266e14e24587498704b070ebb8684880a83b"

[update]
[update.modrinth]
mod-id = "3rc31Hgo"
version = "k3XzTMVx"
