name = "Xaero's World Map"
filename = "XaerosWorldMap_1.21.1_Fabric_1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3779/543/XaerosWorldMap_1.21.1_Fabric_1.18.2.jar"
hash-format = "sha1"
hash = "a6a69786de5d8d3322b367cd24b06c4b3bcf44d9"

[update]
[update.curseforge]
file-id = 3779543
project-id = 317780
